image:
    - Visual Studio 2015
    - Visual Studio 2017

init:
    - git config --global core.autocrlf true

shallow_clone: true

platform:
    - x64
    - x86

configuration:
    - Debug
    - Release

environment:
    matrix:
        # - TOOLCHAIN: msvc10
        # - TOOLCHAIN: msvc12
        - TOOLCHAIN: msvc14
        - TOOLCHAIN: msvc15

matrix:
    fast_finish: false

    exclude:
        -   image: Visual Studio 2015
            TOOLCHAIN: msvc15

        -   image: Visual Studio 2017
            TOOLCHAIN: msvc10

        -   image: Visual Studio 2017
            TOOLCHAIN: msvc12

        -   image: Visual Studio 2017
            TOOLCHAIN: msvc14

install:
    - call ci\appveyor\set-env.bat %TOOLCHAIN% %PLATFORM%

build_script:
    - mkdir build
    - cd build
    - cmake .. %CMAKE_CONFIGURE_FLAGS%
    - cmake --build . %CMAKE_BUILD_FLAGS%

test_script:
    - ctest -C %CONFIGURATION%
